//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professors
    {
        public string JMBAG { get; set; }
        public int RoleID { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<int> CourseID { get; set; }
    
        public virtual Courses Courses { get; set; }
    }
}
