//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTP_Projekt.NTPSoapService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NTPSoapService.NTPSoapSoap")]
    public interface NTPSoapSoap {
        
        // CODEGEN: Generating message contract since element name xmlString from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertXmlToJson", ReplyAction="*")]
        NTP_Projekt.NTPSoapService.ConvertXmlToJsonResponse ConvertXmlToJson(NTP_Projekt.NTPSoapService.ConvertXmlToJsonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertXmlToJson", ReplyAction="*")]
        System.Threading.Tasks.Task<NTP_Projekt.NTPSoapService.ConvertXmlToJsonResponse> ConvertXmlToJsonAsync(NTP_Projekt.NTPSoapService.ConvertXmlToJsonRequest request);
        
        // CODEGEN: Generating message contract since element name jsonString from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertJsonToXml", ReplyAction="*")]
        NTP_Projekt.NTPSoapService.ConvertJsonToXmlResponse ConvertJsonToXml(NTP_Projekt.NTPSoapService.ConvertJsonToXmlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertJsonToXml", ReplyAction="*")]
        System.Threading.Tasks.Task<NTP_Projekt.NTPSoapService.ConvertJsonToXmlResponse> ConvertJsonToXmlAsync(NTP_Projekt.NTPSoapService.ConvertJsonToXmlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertXmlToJsonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertXmlToJson", Namespace="http://tempuri.org/", Order=0)]
        public NTP_Projekt.NTPSoapService.ConvertXmlToJsonRequestBody Body;
        
        public ConvertXmlToJsonRequest() {
        }
        
        public ConvertXmlToJsonRequest(NTP_Projekt.NTPSoapService.ConvertXmlToJsonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertXmlToJsonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlString;
        
        public ConvertXmlToJsonRequestBody() {
        }
        
        public ConvertXmlToJsonRequestBody(string xmlString) {
            this.xmlString = xmlString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertXmlToJsonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertXmlToJsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public NTP_Projekt.NTPSoapService.ConvertXmlToJsonResponseBody Body;
        
        public ConvertXmlToJsonResponse() {
        }
        
        public ConvertXmlToJsonResponse(NTP_Projekt.NTPSoapService.ConvertXmlToJsonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertXmlToJsonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConvertXmlToJsonResult;
        
        public ConvertXmlToJsonResponseBody() {
        }
        
        public ConvertXmlToJsonResponseBody(string ConvertXmlToJsonResult) {
            this.ConvertXmlToJsonResult = ConvertXmlToJsonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertJsonToXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertJsonToXml", Namespace="http://tempuri.org/", Order=0)]
        public NTP_Projekt.NTPSoapService.ConvertJsonToXmlRequestBody Body;
        
        public ConvertJsonToXmlRequest() {
        }
        
        public ConvertJsonToXmlRequest(NTP_Projekt.NTPSoapService.ConvertJsonToXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertJsonToXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonString;
        
        public ConvertJsonToXmlRequestBody() {
        }
        
        public ConvertJsonToXmlRequestBody(string jsonString) {
            this.jsonString = jsonString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConvertJsonToXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConvertJsonToXmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public NTP_Projekt.NTPSoapService.ConvertJsonToXmlResponseBody Body;
        
        public ConvertJsonToXmlResponse() {
        }
        
        public ConvertJsonToXmlResponse(NTP_Projekt.NTPSoapService.ConvertJsonToXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConvertJsonToXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConvertJsonToXmlResult;
        
        public ConvertJsonToXmlResponseBody() {
        }
        
        public ConvertJsonToXmlResponseBody(string ConvertJsonToXmlResult) {
            this.ConvertJsonToXmlResult = ConvertJsonToXmlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NTPSoapSoapChannel : NTP_Projekt.NTPSoapService.NTPSoapSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NTPSoapSoapClient : System.ServiceModel.ClientBase<NTP_Projekt.NTPSoapService.NTPSoapSoap>, NTP_Projekt.NTPSoapService.NTPSoapSoap {
        
        public NTPSoapSoapClient() {
        }
        
        public NTPSoapSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NTPSoapSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NTPSoapSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NTPSoapSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NTP_Projekt.NTPSoapService.ConvertXmlToJsonResponse NTP_Projekt.NTPSoapService.NTPSoapSoap.ConvertXmlToJson(NTP_Projekt.NTPSoapService.ConvertXmlToJsonRequest request) {
            return base.Channel.ConvertXmlToJson(request);
        }
        
        public string ConvertXmlToJson(string xmlString) {
            NTP_Projekt.NTPSoapService.ConvertXmlToJsonRequest inValue = new NTP_Projekt.NTPSoapService.ConvertXmlToJsonRequest();
            inValue.Body = new NTP_Projekt.NTPSoapService.ConvertXmlToJsonRequestBody();
            inValue.Body.xmlString = xmlString;
            NTP_Projekt.NTPSoapService.ConvertXmlToJsonResponse retVal = ((NTP_Projekt.NTPSoapService.NTPSoapSoap)(this)).ConvertXmlToJson(inValue);
            return retVal.Body.ConvertXmlToJsonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NTP_Projekt.NTPSoapService.ConvertXmlToJsonResponse> NTP_Projekt.NTPSoapService.NTPSoapSoap.ConvertXmlToJsonAsync(NTP_Projekt.NTPSoapService.ConvertXmlToJsonRequest request) {
            return base.Channel.ConvertXmlToJsonAsync(request);
        }
        
        public System.Threading.Tasks.Task<NTP_Projekt.NTPSoapService.ConvertXmlToJsonResponse> ConvertXmlToJsonAsync(string xmlString) {
            NTP_Projekt.NTPSoapService.ConvertXmlToJsonRequest inValue = new NTP_Projekt.NTPSoapService.ConvertXmlToJsonRequest();
            inValue.Body = new NTP_Projekt.NTPSoapService.ConvertXmlToJsonRequestBody();
            inValue.Body.xmlString = xmlString;
            return ((NTP_Projekt.NTPSoapService.NTPSoapSoap)(this)).ConvertXmlToJsonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NTP_Projekt.NTPSoapService.ConvertJsonToXmlResponse NTP_Projekt.NTPSoapService.NTPSoapSoap.ConvertJsonToXml(NTP_Projekt.NTPSoapService.ConvertJsonToXmlRequest request) {
            return base.Channel.ConvertJsonToXml(request);
        }
        
        public string ConvertJsonToXml(string jsonString) {
            NTP_Projekt.NTPSoapService.ConvertJsonToXmlRequest inValue = new NTP_Projekt.NTPSoapService.ConvertJsonToXmlRequest();
            inValue.Body = new NTP_Projekt.NTPSoapService.ConvertJsonToXmlRequestBody();
            inValue.Body.jsonString = jsonString;
            NTP_Projekt.NTPSoapService.ConvertJsonToXmlResponse retVal = ((NTP_Projekt.NTPSoapService.NTPSoapSoap)(this)).ConvertJsonToXml(inValue);
            return retVal.Body.ConvertJsonToXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NTP_Projekt.NTPSoapService.ConvertJsonToXmlResponse> NTP_Projekt.NTPSoapService.NTPSoapSoap.ConvertJsonToXmlAsync(NTP_Projekt.NTPSoapService.ConvertJsonToXmlRequest request) {
            return base.Channel.ConvertJsonToXmlAsync(request);
        }
        
        public System.Threading.Tasks.Task<NTP_Projekt.NTPSoapService.ConvertJsonToXmlResponse> ConvertJsonToXmlAsync(string jsonString) {
            NTP_Projekt.NTPSoapService.ConvertJsonToXmlRequest inValue = new NTP_Projekt.NTPSoapService.ConvertJsonToXmlRequest();
            inValue.Body = new NTP_Projekt.NTPSoapService.ConvertJsonToXmlRequestBody();
            inValue.Body.jsonString = jsonString;
            return ((NTP_Projekt.NTPSoapService.NTPSoapSoap)(this)).ConvertJsonToXmlAsync(inValue);
        }
    }
}
